remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
title: "lol no generics"
name: "Alex Milkov"
description: "I'm currently a Scala dev at The Weather Company"
paginate: 5
paginate_path: /page:num/

jekyll:
  environment: 'production'

include:
  - _pages

twitter:
  username: &twitter "amilkov3"
social:
  name: "Alex Milkov"

comments:
  provider: "disqus"
  disqus:
    shortname: "milkovml"

author:
  name: *name
  avatar: "/assets/images/me.png"
  bio: "<code>Stream[F[_], P]</code> into my brain. Scala dev @ The Weather Company (IBM)"
  location: "Everywhere, Earth"
  github: "amilkov3"
  instagram: "amilkov3"
  twitter: *twitter
  links:
    - label: "Resume"
      icon: "fas fa-fw fa-toilet-paper"
      url: "/assets/resume.pdf"

defaults:
  # _posts:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

repository: amilkov3/lol-no-generics

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true

plugins:
  - jekyll-include-cache
