remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
title: "👋"
name: "Alex Milkov"
description: ""
paginate: 5
paginate_path: /page:num/

#gems:
#- jekyll-font-awesome-sass

jekyll:
  environment: 'production'

font-awesome:
  assets: true

exclude:
  - resume/node_modules

include:
  - _pages

comments:
  provider: "disqus"
  disqus:
    shortname: "milkovml"

author:
  name: "Alex Milkov"
  avatar: "/assets/images/me.jpg"
  bio: "<i>Now</i>: Go/Rust/gRPC/MySQL/Elasticsearch @ <a href='https://block.xyz/'>Block (formerly Square)</a><br/><i>Previous</i>: Scala/Clojure/MongoDB @ The Weather Company (IBM)"
  location: "Atlanta, GA"
  links:
    - label: "Twitter"
      icon: "fab fa-twitter-square"
      url: "https://twitter.com/amilkov3"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amilkov3"
    - label: "Resume"
      icon: "fas fa-toilet-paper"
      url: "/resume/resume.html"

defaults:
  # _posts:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

repository: amilkov3/lol-no-generics

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true

plugins:
  - jekyll-include-cache
  - jekyll-font-awesome-sass

