remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
title: "lol no generics"
name: "Alex Milkov"
description: "I'm currently a Scala dev at The Weather Company"
paginate: 5
paginate_path: /page:num/

include:
  - _pages

twitter:
  username: &twitter "amilkov3"
social:
  name: "Alex Milkov"

comments:
  provider: "staticman_v2"
  disqus:
    shortname            :

staticman:
  branch: gh-pages

author:
  name: *name
  avatar: "/assets/images/me.png"
  bio: "I like to `Stream[F[_], P]` into my brain. Currently a Scala dev at The Weather Company"
  location: "Everywhere, Earth"
  github: "amilkov3"
  instagram: "amilkov3"
  twitter: *twitter

defaults:
  # _posts:
  -scope:
    path: ""
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
